version = "1.1.13"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
client = "{icon}"
client_active = "<span>{icon}</span>"
workspace = "<b><span>{id}:</span></b>{delim}{clients}"
workspace_empty = "<b><span color='grey'>{id}:</span></b>{delim}{clients}"
client_dup = "{icon}{counter_sup}{delim}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
client_fullscreen = "[{icon}]{delim}"

# regex captures support is supported
[title_in_class."(?i)foot"]
"emerge: (.+?/.+?)-.*" = "{match1}"

[title_in_class."(brave-browser|firefox|chrom.*)"]
"(?i)youtube" = ""
"(?i)github" = "<span color='grey'></span>"

[title_in_class_active."(brave-browser|firefox|chrom.*)"]
"(?i)youtube" = "<span color='red'></span>"
"(?i)github" = ""


[class]
DEFAULT = ""
"(?i)firefox" = "<span color='orange'> </span>"
"(?i)brave-browser" = "<span>󰖟</span>"
"dropdown" = "<span color='yellow'>󰆍</span>"
"foot" = "󰆍"
"chromium" = ""
"(?i)emacs" = "<span color='purple'></span>"
"(?i)waydroid.*" = "droid"
"libreoffice-calc" = ""
"libreoffice-impress" = ""
"libreoffice-startcenter" = ""
"libreoffice-writer" = ""
"pavucontrol" = ""
"(?i)slack" = "󰒱"
"swappy" = ""
"(?i)zathura" = ""
".*transmission.*" = ""
"virt-manager" = ""
"zoom" = ""

[exclude]
"" = "^$" # prevent displaying clients with empty class

# Local Variables
# eval: (rainbow-mode 1)
# End:
